+ rename user and group back to gdm

diff --git a/debian/gdm.postrm b/debian/gdm.postrm
--- a/debian/gdm.postrm
+++ b/debian/gdm.postrm
@@ -27,14 +27,14 @@ if [ "$1" = "purge" ] ; then
 	rm -rf /var/run/gdm
 	rm -rf /var/log/gdm
 	rm -rf /var/cache/gdm
-        if getent passwd Debian-gdm >/dev/null; then
+        if getent passwd gdm >/dev/null; then
                 if [ -x /usr/sbin/deluser ]; then
-                        deluser --system Debian-gdm || echo "Could not remove Debian-gdm user."
+                        deluser --system gdm || echo "Could not remove gdm user."
                 fi
         fi
-        if getent group Debian-gdm >/dev/null; then
+        if getent group gdm >/dev/null; then
                 if [ -x /usr/sbin/delgroup ]; then
-                        delgroup --system Debian-gdm || echo "Could not remove Debian-gdm group."
+                        delgroup --system gdm || echo "Could not remove gdm group."
                 fi
         fi
 fi
